### ISSUE TITLE
playsound

### ISSUE THREAD

**Issue by Misio12320** [TheLimeGlass/SkQuery#6]
Hello. fix the playsound at loop-entity cause it playing sounds at player not entity and add stop sounds, fix my code which on death of player shall playsound but it does not

options:
    Dzwiek: with volume 10 with pitch 1

command /zabicia [<text>]:
    trigger:
        open chest with 1 rows named "&cMuzyka!" to player
        set player's current inventory's slot 0 to note block named "&2Wybuch Creppera"
on inventory click:
    if inventory name of current inventory of player is "&cMuzyka!":
        cancel event
        if clicked slot is 0:
            set {Zabicie:%player%} to "Crepper"
            play sound "entity.creeper.primed" {@Dzwiek} at player
            send "&aOd teraz po zabiciu gracza, uslyszysz &2Creppera&a!" to player
on death of player:
    if attacker is zombie:
        if {Zabicie::%attacker%} is "Crepper":
            send "t" to attacker
            play sound "entity.creeper.primed" {@Dzwiek} at attacker
code it opens gui with name and on kill of player should play sound at attacker which selected in gui

**Comment by TheLimeGlass** [comment]
Use Skript's play sound https://skriptlang.github.io/Skript/effects.html#EffPlaySound

This play raw sound is deprecated in Mojangs code and doesn't work.
