### ISSUE TITLE
SkQuery permission manager doesn't work

### ISSUE THREAD

**Issue by Vulqa** [TheLimeGlass/SkQuery#7]
**Skript Version:** Skript 2.3.6
**Minecraft Version:** Paper version git-Paper-569 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
Code:

```
script options:
     $ use permissions
    
 command /perm:
     trigger:
         add "test.test" to player's permissions
```

**Errors on Reload:**

> permissions  of the player can't have anything added to it (test.sk, line 6: add "test.test" to player's permissions')

**Addons using (including versions):**
Skellett 1.9.6b, Skore 1.0.0, skRayFall 1.9.15, TuSKe 1.8.2-Pikachu-Patch-3, SkQuery 3.6.3

 have tried the different existing methods on the various topics I have read, but always the same problem

**Comment by TheLimeGlass** [comment]
SkQuery doesn't have permissions anymore, that's Skript not having proper changers. It was a trash commit some random did, I urged that it not be added but it got added...

**Comment by TheManchineel** [comment]
> SkQuery doesn't have permissions anymore, that's Skript not having proper changers. It was a trash commit some random did, I urged that it not be added but it got added...

@TheLimeGlass Soo, the only way to do it is to make console execute a LP command?

**Comment by Idani1** [comment]
You can use skuniversal and luckperms. (I only tested in 1.16.5)
